### PR TITLE
Linux fixes

### PR DESCRIPTION
**Pull request by almightykiwi**
Hello, here are a bunch of build fixes on Linux. Like my previous pull request, there should be no logical change.

Feel free to criticize.

### CODE REVIEW

**Comment by BearishSun** [comment]
Looks good to me. Regarding the "inline" modifiers, I might have used that practice in a lot of files. Instead of removing the inline modifiers we might consider moving the methods from .cpp into separate .inl files. In the particular case you did it for, it was probably better to remove inline to avoid including extra headers required by those methods implementations.

**Comment by BearishSun** [comment]
Actually the nvtt.h include fix is wrong. The dependencies have changed locations recently, get the new file paths here:
https://github.com/BearishSun/BansheeEngine/blob/master/Documentation/GitHub/dependencies.md

Also check the new pre-compiled VS2015 dependencies archive to see how the paths look now:
https://github.com/BearishSun/BansheeEngine/blob/master/Documentation/GitHub/compiling.md

**Comment by almightykiwi** [comment]
Ok, thanks for the links, I'll check the documentation ;-). I simply installed the nvtt library with my package manager so I assumed my fix was correct.

Also, when there's an issue with a pull request, I can fix it on my side (by amending / deleting the faulty commits, and force-pushing the modified branch) rather than having you add more commits to fix the issue. This would result in a cleaner history. Of course, few people read the history for now, but it's a good habit to have, in my opinion. (Just a suggestion.)

**Comment by BearishSun** [comment]
Sounds good, we'll handle it that way from now on.

I plan on adding proper way of finding libraries to CMake, right now it just assumes specific paths.

**Pull request merged**
